index:
    path: /
    defaults: { _controller: CarnetBundle:Default:index }
        
add:
    path: /add
    defaults: { _controller: CarnetBundle:Default:add }
    
delete:
    path: /delete/{id}
    defaults: { _controller: CarnetBundle:Default:delete }

afficher:
    path: /afficher/{id}
    defaults: { _controller: CarnetBundle:Default:afficher }

modifier:
    path: /modifier/{id}
    defaults: { _controller: CarnetBundle:Default:modifier }