<?php

namespace CarnetBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
}
